/*INSERT INTO FAMILYMEMBER VALUES(1,"ALEX","FATHER",45);
INSERT INTO FAMILYMEMBER VALUES(1,"ROSE","MOTHER",40);
INSERT INTO FAMILYMEMBER VALUES(1,"SAM","SON",18);
INSERT INTO FAMILYMEMBER VALUES(1,"ANJALI","DAUGHTER",15);*/
