spring:
  application:
    name: spring-cloud-gateway-app

 # cloud:
  #   routes:
   #     - id: helloservice-route
    #      uri: http://localhost:8071
     #     predicates:
      #      - Path=/rest/service/**    
       # - id: factservice-route
       #   uri: http://localhost:8072
        #  predicates:
         #   - Path=/rest/fact/**


 

 
server:
  port: 8073