spring:
  cloud:
    gateway:
      routes:
        - id: serviceB
          uri: lb://MICROSERVICE-A
          predicates:
            - Path=/A/**
          filters:
            - AuthenticationFilter
            
        - id: serviceA
          uri: lb://MICROSERVICE-B
          predicates:
            - Path=/B/**
          filters:
            - AuthenticationFilter
            
        - id: identity-service
          uri: lb://IDENTITY-SERVICE
          predicates:
            - Path=/auth/**
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
      

   
     